spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Auth config
app.jwt.secret=9a67471ec97aa3da1034e440d87363140308dcd301bb2e04368f5c357731681a
app.jwt.expirationMs=86400000
